### ISSUE TITLE
Add user list + search

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#104]
There is currently no overview of users or a way to find a certain user. Since the URLs are not very "user-friendly", user profiles can basically only be viewed via communities or likewise.
A list just like for missions should be added, including an user search. The backend endpoints for this already exist.

-----

### Tasks
- [x] Add user list
- [x] Add user search
- [x] Make usernames in mission slotlist clickable
