### ISSUE TITLE
Implement mission token management for mission creators

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#121]
The backend [now supports mission tokens](https://github.com/MorpheusXAUT/slotlist-backend/issues/80) as an alternative to regular authentication, to be used for embedding mission details and/or slotlist e.g. on a website or forum.
The three newly created endpoints should be added as a modal for mission creators.

-----

### Tasks
- [x] Add display of mission token
- [x] Add generation of new mission token
- [x] Add deletion of mission token
