### ISSUE TITLE
Changelog page + update notification

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#132]
A separate page detailing the latest changes/a full changelog should be added, informing users about any recent feature additions or bugfixes. Admins should have edit access on that page, allowing for new entries to be quickly created using the frontend only.
To increase the visibility of updates, a new notification type could be added, being automatically sent to every user upon button-click by an admin.

-----

### Tasks
- [x] Add Changelog display page
- [x] Add Changelog modify modals for admins
- [x] Add display of new notification

**Comment by MorpheusXAUT** [comment]
While completed on the frontend side, we currently have the problem of no localization being available on the backend - thus not being able to serve appropriately translated changelog content to the user.
This requires the introduction of user language settings for the backend and will thus be postponed until the language task has been completed.
