### ISSUE TITLE
Display logo on community details and associated mission pages

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#15]
The community model should be extended to include a logo, which could be displayed on the community details page as well as the details of missions that are assigned to a community.

Images should be uploaded to the service and hosted (same as e.g. mission banner images, also depending on https://github.com/MorpheusXAUT/slotlist-backend/issues/4). The related backend task is https://github.com/MorpheusXAUT/slotlist-backend/issues/9.

Since this requires more work, the feature will probably not be included in the `1.0.0-beta` release, but a later version.

-----

### Tasks
- [x] ~~Add image upload to community creator~~
- [x] Add image upload to community edit modal
- [x] Display logo on community details page
- [x] ~Display logo on associated mission details page~

**Comment by MorpheusXAUT** [comment]
The mission's detail page can already contain multiple images as well as lots of information - trying to add the community's logo on there somewhere would probably overload it even more.
Closed for now unless a super fancy solution/implementation just pops up by chance during future development.
