### ISSUE TITLE
Add timeout to loading spinner overlay & close on errors

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#17]
At the moment, there is no timeout for the loading spinner overlay whatsoever, furthermore, it sometimes stays displayed after an API call error is caught. This causes the user to wait although the frontend does not actually do any work anymore, forcing them to manually refresh the page.

This behavior can especially be found on the mission pages (due to older/separate loaders being used).

-----

### Tasks
- [ ] Implement timeout for global `working` loading spinner overlay
- [x] Replace all custom loading spinner overlays to be replaced with the global `working` one
- [x] Make sure all caught errors close any loading spinner overlay shown

**Comment by MorpheusXAUT** [comment]
Most of this has been adressed by moving all components to use the global `LoadingOverlaySpinner`.
Timeouts still have to be implemented, but this requires a rework of the `startWorking` dispatch (potentially queuing up messages/making sure only the right messages get removed).

Postponed until after Beta release, since any errors that get caused by this can be "circumvented" by reloading the page.
