### ISSUE TITLE
Migrate to Bootstrap 4 Beta

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#19]
The Bootstrap 4 Beta has been released, `bootstrap-vue` is nearly done with full support and already released an [updated version](https://bootstrap-vue.js.org/).

Since this is not required immediately and probably requires some migration work, it will not be included in the `1.0.0-beta` release, but added at a later date.

-----

### Tasks
- [ ] Update dependency to v4-beta version of `bootstrap-vue`
- [ ] Fix any issues that arise during migration
- [ ] Make sure all third-party components used function properly
