### ISSUE TITLE
Duplicate slot/slot group in mission slotlist editor

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#21]
Sinus suggested being able to duplicate a slot or a whole slot group would make slotlist management way easier for mission creators. This should be doable somewhat easily without backend changes, however might require some additional "magic" for the `orderNumbers`.

Duplicating a slot would simply send the slot's details to the backend.
Duplicating a slot group would first send the group's details to the backend, then bulk-create the slots in the selected group with the new group association.

-----

### Tasks
- [x] Add slot duplication
- [x] Add slot group duplication
- [x] Figure out `orderNumber` magic
