### ISSUE TITLE
Description/short description labeled inconsistently throughout app

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#22]
The frontend labels for `description` and `shortDescription` fields is handled inconsistently throughout the app, with the `description` sometimes being labeled "Detailed description" and the `shortDescription` something being labeled "Description".

This should be solved by renaming the fields to `description` (former `shortDescription`) and `detailedDescription` (former `description`) respectively. This also requires backend changes, but only slight renaming modifications.

-----

### Tasks
- [x] Parse fields from API as `description` and `detailedDescription`
- [x] Update frontend labeling to properly represent field names
- [x] Updated i18n files to reflect label changes
