### ISSUE TITLE
Prevent scrolling to top of page when creating slots/slot groups

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#27]
After creating a slot or slotgroup, the page currently scrolls to the top (due to the alert being shown as a confirmation). This can get tedious, since creating a lot of slots would require loads of scrolling.
As a solution, the page should only scroll up when displaying a warning/error or when forcefully triggered via an extra flag. Regular `success` should not trigger scrolling anymore, thus making this way more userfriendly

-----

### Tasks
- [x] Disable scrolling to top for `success` alerts
- [x] Add flag to force scrolling
- [x] Add automatic scrolling for `warning` and `error` alerts
