### ISSUE TITLE
Associate slot registrations with communities

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#28]
Frontend implementation for backend task https://github.com/MorpheusXAUT/slotlist-backend/issues/15.

When selecting for a slot to be `restricted`, the user has to search for and select a community to restrict the slot to. Only users of that community should be allowed to register for the slot afterwards.
This also requires a typeahead component for an autocompleted search.

-----

### Tasks
- [x] Create Typeahead component for search
- [x] Add Typeahead community search to slot creation and editing
- [x] Restrict registrations to community members for restricted slots
