### ISSUE TITLE
Implement permission granting/revoking for missions

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#57]
Once MorpheusXAUT/slotlist-backend/issues/35 and MorpheusXAUT/slotlist-backend/issues/36 are completed, the frontend needs to add support for editing mission permissions.
A modal with a list of current permissions and a user search for granting new ones would probably be the best solution for that.

-----

### Tasks
- [x] Implement store/API functionality for handling backend endpoints
- [x] Add modal for displaying mission permissions
- [x] Add Typeahead for searching user to add permissions for
