### ISSUE TITLE
Implement permission granting/revoking for missions

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#59]
Once MorpheusXAUT/slotlist-backend#37 is completed, the frontend needs to add support for editing community permissions.
A modal with a list of current permissions and a user search for granting new ones like in #57 should work fine.

-----

### Tasks
- [x] Implement store/API functionality for handling backend endpoints
- [x] Add modal for displaying mission permissions
- [x] Add Typeahead for searching user to add permissions for
