### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#6]
At the moment, all strings are hardcoded and only available in English.
Due to the site being designed for a German ArmA community, i18n including (at least) English and German is required.

The vue-i18n package could be used to achieve this. Language files could be downloaded as JSON from the API ([backend implementation task](https://github.com/MorpheusXAUT/slotlist-backend/issues/2)) and switched depending on the user selection/auto detection (e.g. like [here](https://github.com/ndabAP/Vue.js-with-Sails.js-backend-example-project/blob/67b9b6105a1af087b8c53ab3312cd9de7f3b7ee7/frontend/src/bootstrap.desktop.js) and [here](https://github.com/ndabAP/Vue.js-with-Sails.js-backend-example-project/blob/67b9b6105a1af087b8c53ab3312cd9de7f3b7ee7/frontend/src/App.mixin.js)).

The user's selected browser language could for instance be retrieved via 
```JavaScript
const userLanguage = navigator.language || navigator.userLanguage || navigator.browserLanguage || navigator.systemLanguage;
const languageCode = userLanguage.split('-')[0];
```
which would e.g. return `en` or `de`.

After retrieving the browser language for the first time, the value/changes by the user should be stored in a cookie for persistence. Should the user's browser language not be available in the list of translations retrieved, the fallback `en` will be used.

-----

### Tasks
- [x] vue-i18n integration using vuex
- [x] Migration of all current strings to separate `en.json` file
- [x] ~Serving of language JSON files via API~
- [x] ~Loading of available languages via API~
- [x] User language detection
- [x] User language selection / persistence
- [x] Replacement of all current strings with vue-i18n calls
- [x] Translation to German
- [x] Translate static page (e.g. `Home`, `About`, `Privacy`) in separate components

**Comment by MorpheusXAUT** [comment]
The backend implementation progress can be tracked here: https://github.com/MorpheusXAUT/slotlist-frontend/issues/6

**Comment by MorpheusXAUT** [comment]
Internationalization will be done on the frontend-side only, since it would require additional calls for displaying the basic page navigation, thus increasing the initial load time.

With the new GCP/k8s setup, changes and updates are done easily and quickly anyways, so having to roll out frontend updates is not a hassle anymore.

**Comment by MorpheusXAUT** [comment]
Most component strings have been moved to the `en.json` file, views are currently outstanding though.

**Comment by MorpheusXAUT** [comment]
Strings should all be extracted as of ef843f82db2015538035498c6376ac9d08c7c19e. The `en.json` file is thus preliminarily completed and can be translated to German.
Language detection still needs to be implemented.

**Comment by MorpheusXAUT** [comment]
Translation to German is preliminarily finished. Static pages are still outstanding, but the current version has already been deployed to production for "testing" by others.
