### ISSUE TITLE
Properly set up sentry.io error reporting

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#63]
The current reporting setup that was added while half-asleep is only partially useful (if at all) since it reports errors for every failed API request, including ones that just receive an error-status code from the backend.
All vuex store actions should be checked for their allowed response "failures", only reporting an error for actual frontend issues.

-----

### Tasks
- [x] Fix reporting for auth module
- [x] Fix reporting for communities module
- [x] Fix reporting for missions module
- [x] Fix reporting for users module
- [x] Fix reporting for util module
