### ISSUE TITLE
Separate slotlist into groups

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#7]
Once the [backend task](https://github.com/MorpheusXAUT/slotlist-backend/issues/3) for adding slot groups has been completed, the frontend needs to be adapted as well to reflect the changes to the slot list.

Groups are most likely best implemented as separate tables/"sets" of rows in their own components, providing a visual separation of slots. Furthermore, the groups additional information such as the callsign has to be displayed. It is still to be decided how exactly this should be implemented.. Since the backend will most likely not return the slotlist paginated, it will also be irrelevant for the frontend.

Once the slot list has been updated to include the new changes, the mission edit screen also needs changes so groups can be created and slots can be associated with them.

-----

### Tasks
- [x] Implement changes to API endpoints
- [x] Add separate components for mission groups/slots
- [x] Add mission group creation/assignment to slot list editor
