### ISSUE TITLE
Handle blocked slots

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#70]
Once https://github.com/MorpheusXAUT/slotlist-backend/issues/46 has been implemented, frontend-support has to be added. This includes a new checkbox for slot creation/editing as well as proper display of slots in the slotlist.

-----

### Tasks
- [x] Add checkbox for toggling `blocked` status while creating/editing slots
- [x] Display blocked slots differently in slotlist (including information popover)
- [x] Disable registrations for blocked slots
