### ISSUE TITLE
Add mission calendar to Home page

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#75]
The Home page could further be enhanced by adding a calendar providing an overview of upcoming missions, as requested by a few people.
Possible library candidates to implement this could be [vue-bootstrap4-calendar](https://github.com/ExCluSiv3/Vue-Bootstrap-Calendar) (forked to remove modals and replace them with mission links) or plain [bootstrap-calendar](https://github.com/Serhioromano/bootstrap-calendar), although that would probably require being served as an `iframe` or likewise.

-----

### Tasks
- [x] Decide whether to implement calendar as Vue component or embed it from external source
- [x] Implement mission calendar on Home page
- [x] Add separate endpoint/handling for calendar missions

**Comment by MorpheusXAUT** [comment]
A "fork" of [vue-bootstrap4-calendar](https://github.com/ExCluSiv3/Vue-Bootstrap-Calendar) without the additional, unnecessary functionality such as language change, event creation/editing/deletion or the event modals, will most definitely be the best choice for integration into the Home page.
External sites cannot use this for the moment - a generator might be added at a future point.
