### ISSUE TITLE
Banner image for missions

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#8]
Belbo suggested for an (optional) banner image to be added to the stored mission details, to be displayed below the mission title (an example can be seen [here](http://spezialeinheit-luchs.de/Forum/g/posts/t/1530/02-09-2017-COOP-100-All-Of-Altis)).

This could be implemented as an additional (optional) field upon mission creation and simply be displayed if available, however a decision has to be made between image self-hosting (storage in DB as a data blob same as with the description editor currently), integration into GCP file storage (pricing has to be evaluated) or the requirement for the image to be hosted externally (e.g. on imgur, although this is the least preferred alternative). A related backend task can be found here: https://github.com/MorpheusXAUT/slotlist-backend/issues/4

Sane restrictions for file size and image dimensions (or auto-scaling) has to be evaluated and implemented as well.

Since this requires more work, the feature will probably not be included in the `1.0.0-beta` release, but a later version.

-----

### Tasks
- [x] Evaluate storage options
- [x] Implement appropriate image upload into mission creator/editor (if required)
- [x] Add display of banner image to mission details page
- [x] Evaluate & implement image restrictions
