### ISSUE TITLE
Retrieve user missions via separate endpoint

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#84]
The `UserDetails` endpoint currently relies on the user's mission list to be passed via the detailed user object. Since this does not include pagination, it will introduce long load times once users create multiple missions.
The backend already offers a regular, paginated user mission list endpoint - the frontend should be adapted to use this instead.

-----

### Tasks
- [x] Remove dependency on detailed user object for missions
- [x] Retrieve user missions via endpoint
- [x] Paginate user missions
