### ISSUE TITLE
Allow actions for multiple selected slots

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#88]
Certain actions, such as reserving for a community, deleting, etc. should be possible for multiple slots simultaneously. This requires some sort of multi-select for slots, e.g. via checkboxes or some sort of table selection.
The selection of multiple slot rows is probably the most annoying part about this.

-----

### Tasks
- [x] Implement multi selection for tables
- [x] Add edit action for slot multi selection
- [x] Add delete action for slot multi selection
