### ISSUE TITLE
Add mission visibility to details/editor

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#9]
https://github.com/MorpheusXAUT/slotlist-backend/issues/5 introduces a `visibility` setting to all missions. Whilst the regular mission list requires no changes, the setting should be displayed on the mission details page and be changeable for mission creators/editors. Furthermore, the desired setting should be selectable during mission creation.

-----

### Tasks
- [x] Display `visibility` value on mission details page
- [x] Add `select` for modifying the `visibility` setting of an existing mission
- [x] Add `select` for choosing `visibility` setting while creating a mission
