### ISSUE TITLE
Mission slot templates

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-frontend#93]
Once https://github.com/MorpheusXAUT/slotlist-backend/issues/59 is done, frontend support for mission slot templates needs to be added.
A new creator for mission slot templates needs to be added, maybe also including the option to generate a new template from an existing mission.
Since no reordering is done via the backend, the frontend is in charge of creating a correct order for slots and groups, however this should be relatively easy to implement with client-side `move up`/`move down` buttons.
The mission slotlist then needs to have a modal displaying all available mission slot templates and allowing them to be added to the mission.

-----

### Tasks
- [x] Add mission slot template list
- [x] Add mission slot template details
- [x] Add mission slot template creator
- [x] Implement mission slot template editor
- [x] Implement mission slot template slotlist editor
- [x] Allow for existing missions to be converted to a slot template
- [x] Implement mission slot template selection modal
